name: stock-screener

on:
  schedule:
    - cron: '30 6 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Pythonセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: ライブラリインストール
        run: |
          pip install yfinance pandas numpy tqdm requests openpyxl

      - name: 実行
        run: python スクリーナー.py
